Hello: Hello
NoTeachers: There are not teachers created yet. Please be patient.
NewTeacher: Add a teacher
ListTeachers: List all teachers
ListReviewedTeachers: List reviewed teachers
ListReportedReviews: List reported reviews
ProposeTeacher: Propose a teacher
ListUsers: List all users
Login: Log in
Logout: Log out
EditTeacher: Edit
DeleteTeacher: Delete
AdminTitle: Admin Zone
TeacherCreated: The teacher was successfully created
CreateTeacher: Create a teacher
UserBlocked: The user has been blocked
TeacherDeleted: The teacher was deleted
TeacherUpdated: The teacher was successfully updated
ShowTeacher: Teacher details 