Default: &defaults
  database: expose-a-teacher-yesod.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: expose-a-teacher-yesod_test.sqlite3
  <<: *defaults

Staging:
  database: expose-a-teacher-yesod_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: expose-a-teacher-yesod_production.sqlite3
  poolsize: 100
  <<: *defaults
